### ISSUE TITLE
ES6 Promises optional support 

### ISSUE THREAD

**Issue by MarcCloud** [d-oliveros/isomorphine#3]
I have been working with this library API for the last month and I think its a great step forward on dev tools that help to achieve true isomorphic apps.

Just as a feature request I would like to have the option to use ES6 promises instead of callbacks.

I can work on a PR for that if time allows.

**Comment by d-oliveros** [comment]
Thanks MarcCloud! I'm sorry for the late response, somehow I had the notifications for this repo muted.

I haven't been able to update the README.md, but isomorphine already supports promises. Just return a promise in your module's exported function, and isomorphine will wait for the promise to be resolved and rejected.

In the browser, when calling a promise-based function, a promise will be returned, and it will be resolved with the server's response. In the server, when a request to a promise-based function is made, it will check if the function returns a promise, and wait for the promise to be resolved.

I'll try to update the README.md this weekend. I'll gladly merge a PR too if someone wants to update it.

Cheers!
