### ISSUE TITLE
host/port shouldn't require additional quotes

### ISSUE THREAD

**Issue by tejacques** [d-oliveros/isomorphine#4]
Can this just be updated in the loader to work with regular strings?

**Comment by d-oliveros** [comment]
Yes, this needs to be changed. I'm actually deprecating the webpack-based configuration, in favor for a in-code configuration:

![2015-12-11-12 26 54-screenshot](https://cloud.githubusercontent.com/assets/2173299/11751966/83b489dc-a002-11e5-9bb8-ae96bb9ec9e9.png)

Let me know what you think :smile:

**Comment by d-oliveros** [comment]
Hey @tejacques, I've just updated the README.md, and removed the webpack-based configuration: https://github.com/d-oliveros/isomorphine#usage.

I'll close this for now. Feel free to reopen this issue if you experience issues with this way of configuring Isomorphine.
